name: "Build and deploy kaif-app app in AWS"

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read
  
jobs:
  build-kaif-app:
    runs-on: ubuntu-22.04
    container:
      image: 18.16.0-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install npm dependencies
        run: npm install
      - name: Build the project
        run: npm run build
        env:
          DISABLE_ESLINT_PLUGIN: true # Attention! Use this feature only in test workflows.
      - name: Save app build
        uses: actions/upload-artifact@v3
        with:
          name: build-kaif-app
          path: /build
          retention-days: 1
          
  upload-kaif-app:
    needs:
      - build-kaif-app
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-kaif-app
          path: build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ARN_ROLE }}
          aws-region: us-east-1
      - name: Upload files
        run: aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME}}/
        
  invalidate-cdn-cache:
    needs:
      - upload-kaif-app
    runs-on: ubuntu-22.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ARN_ROLE }}
          aws-region: us-east-1
      - name: Invalidate cache 
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"